Repository Team-KekX/Ardas-Legends-App, pull requests merged in 2024-01, with the labels that each got.

#130 Rework Applications
  pom.xml
  src/main/java/com/ardaslegends/domain/applications/AbstractApplication.java
  src/main/java/com/ardaslegends/domain/applications/ClaimbuildApplication.java
  src/main/java/com/ardaslegends/domain/applications/RoleplayApplication.java
  src/main/java/com/ardaslegends/presentation/api/application/ClaimbuildApplicationController.java
  src/main/java/com/ardaslegends/presentation/api/application/RoleplayApplicationController.java
  src/main/java/com/ardaslegends/service/applications/ClaimbuildApplicationService.java
  src/main/java/com/ardaslegends/service/applications/RoleplayApplicationService.java
  src/main/java/com/ardaslegends/service/exceptions/logic/applications/ApplicationException.java
  src/test/java/com/ardaslegends/presentation/api/ArmyRestControllerTest.java
  src/test/java/com/ardaslegends/service/ClaimbuildAppServiceTest.java
Labels: Applications, Backend

#129 Fixed MovementResponse using the wrong value for hoursUntilNextRegion
  src/main/java/com/ardaslegends/presentation/api/response/movement/MovementResponse.java
Labels: bug, Backend

#133 Complete ArmyResponse Attributes
  src/main/java/com/ardaslegends/presentation/api/response/army/ArmyResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/unit/UnitResponse.java
  src/test/java/com/ardaslegends/presentation/api/ArmyRestControllerTest.java
Labels: bug, Backend

#134 Bug#132/missing timezone information
  src/main/java/com/ardaslegends/configuration/WebConfig.java
  src/main/java/com/ardaslegends/domain/Army.java
  src/main/java/com/ardaslegends/domain/Movement.java
  src/main/java/com/ardaslegends/domain/RPChar.java
  src/main/java/com/ardaslegends/domain/applications/AbstractApplication.java
  src/main/java/com/ardaslegends/domain/war/Battle.java
  src/main/java/com/ardaslegends/domain/war/War.java
  src/main/java/com/ardaslegends/domain/war/WarParticipant.java
  src/main/java/com/ardaslegends/presentation/api/response/applications/ClaimbuildApplicationResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/applications/RoleplayApplicationResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/army/ArmyResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/movement/MovementResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/player/rpchar/RpCharOwnerResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/player/rpchar/RpCharResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/war/ActiveWarResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/war/PaginatedWarsResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/war/WarParticipantResponse.java
  src/main/java/com/ardaslegends/service/ArmyService.java
  src/main/java/com/ardaslegends/service/MovementService.java
  src/main/java/com/ardaslegends/service/ScheduleService.java
  src/main/java/com/ardaslegends/service/applications/ClaimbuildApplicationService.java
  src/main/java/com/ardaslegends/service/applications/RoleplayApplicationService.java
  src/main/java/com/ardaslegends/service/war/BattleService.java
  src/main/puml/ArdasLegendsDomain.puml
  src/test/java/com/ardaslegends/presentation/api/ArmyRestControllerTest.java
  src/test/java/com/ardaslegends/service/ArmyServiceTest.java
  src/test/java/com/ardaslegends/service/MovementServiceTest.java
  src/test/java/com/ardaslegends/service/ScheduleServiceTest.java
  src/test/resources/schema.sql
Labels: bug, improvement, Backend

#137 Fetch and Calculate Movement Endpoints
  src/main/java/com/ardaslegends/presentation/api/MovementRestController.java
  src/main/java/com/ardaslegends/presentation/api/response/movement/CurrentAndPastMovementResponse.java
  src/main/java/com/ardaslegends/repository/MovementRepository.java
  src/main/java/com/ardaslegends/repository/rpchar/RpcharRepository.java
  src/main/java/com/ardaslegends/service/MovementService.java
  src/main/java/com/ardaslegends/service/RpCharService.java
  src/test/java/com/ardaslegends/presentation/api/MovementRestControllerTest.java
  src/test/java/com/ardaslegends/service/MovementServiceTest.java
Labels: Backend

#142 Update to Spring boot 3.2.2
  pom.xml
Labels: enhancement, Backend

#145 Feature#144/new discord message interface
  src/main/java/com/ardaslegends/service/discord/DiscordService.java
  src/main/java/com/ardaslegends/service/discord/messages/ALMessage.java
  src/main/java/com/ardaslegends/service/discord/messages/war/WarMessages.java
  src/main/java/com/ardaslegends/service/war/WarService.java
Labels: enhancement, War Update, Backend

#146 Feature#136/end war for staff
  src/main/java/com/ardaslegends/domain/Faction.java
  src/main/java/com/ardaslegends/domain/war/War.java
  src/main/java/com/ardaslegends/domain/war/WarParticipant.java
  src/main/java/com/ardaslegends/presentation/api/WarRestController.java
  src/main/java/com/ardaslegends/presentation/discord/commands/Commands.java
  src/main/java/com/ardaslegends/presentation/discord/commands/declare/DeclareCommand.java
  src/main/java/com/ardaslegends/presentation/discord/commands/declare/DeclareWarCommand.java
  src/main/java/com/ardaslegends/presentation/discord/utils/Thumbnails.java
  src/main/java/com/ardaslegends/repository/WarRepository.java
  src/main/java/com/ardaslegends/repository/exceptions/NotFoundException.java
  src/main/java/com/ardaslegends/service/Pathfinder.java
  src/main/java/com/ardaslegends/service/discord/DiscordService.java
  src/main/java/com/ardaslegends/service/discord/messages/war/WarMessages.java
  src/main/java/com/ardaslegends/service/dto/war/EndWarDto.java
  src/main/java/com/ardaslegends/service/exceptions/logic/war/WarServiceException.java
  src/main/java/com/ardaslegends/service/exceptions/permission/StaffPermissionException.java
  src/main/java/com/ardaslegends/service/war/WarService.java
Labels: enhancement, War Update, Backend

#151 Feature#150/remove wrapped service execution
  src/main/java/com/ardaslegends/presentation/AbstractRestController.java
  src/main/java/com/ardaslegends/presentation/api/ArmyRestController.java
  src/main/java/com/ardaslegends/presentation/api/ClaimbuildRestController.java
  src/main/java/com/ardaslegends/presentation/api/FactionRestController.java
  src/main/java/com/ardaslegends/presentation/api/MovementRestController.java
  src/main/java/com/ardaslegends/presentation/api/PlayerRestController.java
  src/main/java/com/ardaslegends/presentation/api/ProductionSiteController.java
  src/main/java/com/ardaslegends/presentation/api/RegionController.java
  src/main/java/com/ardaslegends/presentation/api/RpCharRestController.java
  src/main/java/com/ardaslegends/presentation/api/WarRestController.java
  src/main/java/com/ardaslegends/presentation/api/application/ClaimbuildApplicationController.java
  src/main/java/com/ardaslegends/presentation/api/application/RoleplayApplicationController.java
  src/test/java/com/ardaslegends/presentation/AbstractRestControllerTest.java
Labels: Backend, Refactoring

#149 Feature#075/declaring battles
  src/main/java/com/ardaslegends/domain/Army.java
  src/main/java/com/ardaslegends/domain/Movement.java
  src/main/java/com/ardaslegends/domain/PathElement.java
  src/main/java/com/ardaslegends/domain/RegionType.java
  src/main/java/com/ardaslegends/domain/war/Battle.java
  src/main/java/com/ardaslegends/domain/war/BattleLocation.java
  src/main/java/com/ardaslegends/domain/war/War.java
  src/main/java/com/ardaslegends/domain/war/WarParticipant.java
  src/main/java/com/ardaslegends/presentation/api/WarRestController.java
  src/main/java/com/ardaslegends/presentation/api/response/war/BattleResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/war/PaginatedWarsResponse.java
  src/main/java/com/ardaslegends/presentation/api/response/war/WarResponse.java
  src/main/java/com/ardaslegends/presentation/exceptions/RestExceptionHandler.java
  src/main/java/com/ardaslegends/repository/exceptions/DataAccessException.java
  src/main/java/com/ardaslegends/repository/exceptions/NotFoundException.java
  src/main/java/com/ardaslegends/repository/exceptions/RepositoryException.java
  src/main/java/com/ardaslegends/repository/exceptions/RepositoryNullPointerException.java
  src/main/java/com/ardaslegends/repository/war/QueryWarStatus.java
  src/main/java/com/ardaslegends/repository/war/WarRepository.java
  src/main/java/com/ardaslegends/repository/war/WarRepositoryCustom.java
  src/main/java/com/ardaslegends/repository/war/WarRepositoryImpl.java
  src/main/java/com/ardaslegends/service/applications/ClaimbuildApplicationService.java
  src/main/java/com/ardaslegends/service/dto/war/CreateBattleDto.java
  src/main/java/com/ardaslegends/service/exceptions/logic/applications/ClaimbuildApplicationException.java
  src/main/java/com/ardaslegends/service/exceptions/logic/war/BattleServiceException.java
  src/main/java/com/ardaslegends/service/utils/ServiceUtils.java
  src/main/java/com/ardaslegends/service/war/BattleService.java
  src/main/java/com/ardaslegends/service/war/WarService.java
  src/main/resources/application.properties
  src/test/java/com/ardaslegends/repository/WarRepositoryTest.java
  src/test/java/com/ardaslegends/service/BattleServiceTest.java
Labels: enhancement, War Update, Backend

#155 Upgraded java version to 21
  .github/workflows/maven.yml
  pom.xml
Labels: improvement, War Update, Backend
